name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: "murmure-rapide"
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        version: 'latest'
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY_ARTIFACT }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud --quiet auth configure-docker --project ${{ env.PROJECT_ID }}
    
    - name: Build Docker image
      run: |
        docker build \
        -f Dockerfile.cuda \
        -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest \
        -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA .
    
    - name: Push Docker image to Artifact Registry
      run: |
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
